/*
 * ex: set ro:
 * DO NOT EDIT.
 * generated by smc (http://smc.sourceforge.net/)
 * from file : KotlinNativeBot.sm
 */


public class KotlinNativeBotContext
    extends statemap.FSMContext
{
//---------------------------------------------------------------
// Member methods.
//

    public KotlinNativeBotContext(KotlinNativeBot owner)
    {
        this (owner, MainMap.Idle);
    }

    public KotlinNativeBotContext(KotlinNativeBot owner, KotlinNativeBotState initState)
    {
        super (initState);

        mOwner = owner;
    }

    @Override
    public void enterStartState()
    {
        getState().entry(this);
    }

    public void reset()
    {
        mTransition = "reset";
        getState().reset(this);
        mTransition = "";
    }

    public void startTask(String task)
    {
        mTransition = "startTask";
        getState().startTask(this, task);
        mTransition = "";
    }

    public void taskComplete()
    {
        mTransition = "taskComplete";
        getState().taskComplete(this);
        mTransition = "";
    }

    public void taskFailed()
    {
        mTransition = "taskFailed";
        getState().taskFailed(this);
        mTransition = "";
    }

    public KotlinNativeBotState getState()
        throws statemap.StateUndefinedException
    {
        if (mState == null)
        {
            throw(
                new statemap.StateUndefinedException());
        }

        return ((KotlinNativeBotState) mState);
    }

    protected KotlinNativeBot getOwner()
    {
        return (mOwner);
    }

    public void setOwner(KotlinNativeBot owner)
    {
        if (owner == null)
        {
            throw (
                new NullPointerException(
                    "null owner"));
        }
        else
        {
            mOwner = owner;
        }
    }

//---------------------------------------------------------------
// Member data.
//

    private transient KotlinNativeBot mOwner;

    //-----------------------------------------------------------
    // Constants.
    //

    private static final long serialVersionUID = 1L;

//---------------------------------------------------------------
// Inner classes.
//

    public static abstract class KotlinNativeBotState
        extends statemap.State
    {
    //-----------------------------------------------------------
    // Member methods.
    //

        protected KotlinNativeBotState(String name, int id)
        {
            super (name, id);
        }

        protected void entry(KotlinNativeBotContext context) {}
        protected void exit(KotlinNativeBotContext context) {}

        protected void reset(KotlinNativeBotContext context)
        {
            Default(context);
        }

        protected void startTask(KotlinNativeBotContext context, String task)
        {
            Default(context);
        }

        protected void taskComplete(KotlinNativeBotContext context)
        {
            Default(context);
        }

        protected void taskFailed(KotlinNativeBotContext context)
        {
            Default(context);
        }

        protected void Default(KotlinNativeBotContext context)
        {
            throw (
                new statemap.TransitionUndefinedException(
                    "State: " +
                    context.getState().getName() +
                    ", Transition: " +
                    context.getTransition()));
        }

    //-----------------------------------------------------------
    // Member data.
    //

        //-------------------------------------------------------
    // Constants.
    //

        private static final long serialVersionUID = 1L;
    }

    /* package */ static abstract class MainMap
    {
    //-----------------------------------------------------------
    // Member methods.
    //

    //-----------------------------------------------------------
    // Member data.
    //

        //-------------------------------------------------------
        // Constants.
        //

        public static final MainMap_Idle Idle =
            new MainMap_Idle("MainMap.Idle", 0);
        public static final MainMap_Working Working =
            new MainMap_Working("MainMap.Working", 1);
        public static final MainMap_Error Error =
            new MainMap_Error("MainMap.Error", 2);
    }

    protected static class MainMap_Default
        extends KotlinNativeBotState
    {
    //-----------------------------------------------------------
    // Member methods.
    //

        protected MainMap_Default(String name, int id)
        {
            super (name, id);
        }

    //-----------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class MainMap_Idle
        extends MainMap_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private MainMap_Idle(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void startTask(KotlinNativeBotContext context, String task)
        {
            KotlinNativeBot ctxt = context.getOwner();

            (context.getState()).exit(context);
            context.clearState();
            try
            {
                ctxt.start(task);
            }
            finally
            {
                context.setState(MainMap.Working);
                (context.getState()).entry(context);
            }


        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class MainMap_Working
        extends MainMap_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private MainMap_Working(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void taskComplete(KotlinNativeBotContext context)
        {
            KotlinNativeBot ctxt = context.getOwner();

            (context.getState()).exit(context);
            context.clearState();
            try
            {
                ctxt.log("Task complete");
            }
            finally
            {
                context.setState(MainMap.Idle);
                (context.getState()).entry(context);
            }


        }

        @Override
        protected void taskFailed(KotlinNativeBotContext context)
        {
            KotlinNativeBot ctxt = context.getOwner();

            (context.getState()).exit(context);
            context.clearState();
            try
            {
                ctxt.log("Task failed");
            }
            finally
            {
                context.setState(MainMap.Error);
                (context.getState()).entry(context);
            }


        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class MainMap_Error
        extends MainMap_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private MainMap_Error(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void reset(KotlinNativeBotContext context)
        {
            KotlinNativeBot ctxt = context.getOwner();

            (context.getState()).exit(context);
            context.clearState();
            try
            {
                ctxt.log("Resetting");
            }
            finally
            {
                context.setState(MainMap.Idle);
                (context.getState()).entry(context);
            }


        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }
}

/*
 * Local variables:
 *  buffer-read-only: t
 * End:
 */
