//
// ex: set ro:
// DO NOT EDIT.
// generated by smc (http://smc.sourceforge.net/)
// from file : ReactNativeBot.sm
//

#ifndef REACTNATIVEBOT_SM_H
#define REACTNATIVEBOT_SM_H


#define SMC_USES_IOSTREAMS

#include <statemap.h>

// Forward declarations.
class MainMap;
class MainMap_Idle;
class MainMap_Working;
class MainMap_Error;
class MainMap_Default;
class ReactNativeBotState;
class ReactNativeBotContext;
class ReactNativeBot;

class ReactNativeBotState :
    public statemap::State
{
public:

    ReactNativeBotState(const char * const name, const int stateId)
    : statemap::State(name, stateId)
    {};

    virtual void Entry(ReactNativeBotContext&) {};
    virtual void Exit(ReactNativeBotContext&) {};

    virtual void reset(ReactNativeBotContext& context);
    virtual void startTask(ReactNativeBotContext& context, std::string task);
    virtual void taskComplete(ReactNativeBotContext& context);
    virtual void taskFailed(ReactNativeBotContext& context);

protected:

    virtual void Default(ReactNativeBotContext& context);
};

class MainMap
{
public:

    static MainMap_Idle Idle;
    static MainMap_Working Working;
    static MainMap_Error Error;
};

class MainMap_Default :
    public ReactNativeBotState
{
public:

    MainMap_Default(const char * const name, const int stateId)
    : ReactNativeBotState(name, stateId)
    {};

};

class MainMap_Idle :
    public MainMap_Default
{
public:
    MainMap_Idle(const char * const name, const int stateId)
    : MainMap_Default(name, stateId)
    {};

    virtual void startTask(ReactNativeBotContext& context, std::string task);
};

class MainMap_Working :
    public MainMap_Default
{
public:
    MainMap_Working(const char * const name, const int stateId)
    : MainMap_Default(name, stateId)
    {};

    virtual void taskComplete(ReactNativeBotContext& context);
    virtual void taskFailed(ReactNativeBotContext& context);
};

class MainMap_Error :
    public MainMap_Default
{
public:
    MainMap_Error(const char * const name, const int stateId)
    : MainMap_Default(name, stateId)
    {};

    virtual void reset(ReactNativeBotContext& context);
};

class ReactNativeBotContext :
    public statemap::FSMContext
{
public:

    explicit ReactNativeBotContext(ReactNativeBot& owner)
    : FSMContext(MainMap::Idle),
      _owner(owner)
    {};

    ReactNativeBotContext(ReactNativeBot& owner, const statemap::State& state)
    : FSMContext(state),
      _owner(owner)
    {};

    virtual void enterStartState()
    {
        getState().Entry(*this);
        return;
    }

    inline ReactNativeBot& getOwner()
    {
        return (_owner);
    };

    inline ReactNativeBotState& getState()
    {
        if (_state == NULL)
        {
            throw statemap::StateUndefinedException();
        }

        return dynamic_cast<ReactNativeBotState&>(*_state);
    };

    inline void reset()
    {
        getState().reset(*this);
    };

    inline void startTask(std::string task)
    {
        getState().startTask(*this, task);
    };

    inline void taskComplete()
    {
        getState().taskComplete(*this);
    };

    inline void taskFailed()
    {
        getState().taskFailed(*this);
    };

private:
    ReactNativeBot& _owner;
};


#endif // REACTNATIVEBOT_SM_H

//
// Local variables:
//  buffer-read-only: t
// End:
//
