//
// ex: set ro:
// DO NOT EDIT.
// generated by smc (http://smc.sourceforge.net/)
// from file : ReactNativeBot.sm
//

#include "ReactNativeBot.h"
#include "src/ReactNativeBot_sm.h"

using namespace statemap;

// Static class declarations.
MainMap_Idle MainMap::Idle("MainMap::Idle", 0);
MainMap_Working MainMap::Working("MainMap::Working", 1);
MainMap_Error MainMap::Error("MainMap::Error", 2);

void ReactNativeBotState::reset(ReactNativeBotContext& context)
{
    Default(context);
}

void ReactNativeBotState::startTask(ReactNativeBotContext& context, std::string task)
{
    Default(context);
}

void ReactNativeBotState::taskComplete(ReactNativeBotContext& context)
{
    Default(context);
}

void ReactNativeBotState::taskFailed(ReactNativeBotContext& context)
{
    Default(context);
}

void ReactNativeBotState::Default(ReactNativeBotContext& context)
{
    throw (
        TransitionUndefinedException(
            (context.getState()).getName(),
            context.getTransition()));

}

void MainMap_Idle::startTask(ReactNativeBotContext& context, std::string task)
{
    ReactNativeBot& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.start(task);
        context.setState(MainMap::Working);
    }
    catch (...)
    {
        context.setState(MainMap::Working);
        throw;
    }
    context.getState().Entry(context);


}

void MainMap_Working::taskComplete(ReactNativeBotContext& context)
{
    ReactNativeBot& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.log("Task complete");
        context.setState(MainMap::Idle);
    }
    catch (...)
    {
        context.setState(MainMap::Idle);
        throw;
    }
    context.getState().Entry(context);


}

void MainMap_Working::taskFailed(ReactNativeBotContext& context)
{
    ReactNativeBot& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.log("Task failed");
        context.setState(MainMap::Error);
    }
    catch (...)
    {
        context.setState(MainMap::Error);
        throw;
    }
    context.getState().Entry(context);


}

void MainMap_Error::reset(ReactNativeBotContext& context)
{
    ReactNativeBot& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.log("Resetting");
        context.setState(MainMap::Idle);
    }
    catch (...)
    {
        context.setState(MainMap::Idle);
        throw;
    }
    context.getState().Entry(context);


}

//
// Local variables:
//  buffer-read-only: t
// End:
//
